# Generated by Django 3.0.5 on 2020-04-09 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=255, null=True)),
                ('placas', models.CharField(max_length=255, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=15, default=0.0, max_digits=20)),
                ('lng', models.DecimalField(blank=True, decimal_places=15, default=0.0, max_digits=20)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
